replicaCount: 1

image:
  repository: prathmeshwake/nr-bank-app-helm-full
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  nodePort: 30080

newRelic:
  licenseKey: "provide your license key"
