replicaCount: 1

image:
  repository: prathmeshwake/nr-bank-app-helm-full
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePorts
  port: 3000
  nodePort: 30080

newRelic:
  licenseKey: "517e6644f89f38d856113b759b67439dFFFFNRAL"
