apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nr-bank-app.fullname" . }}
  labels:
    app: {{ include "nr-bank-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nr-bank-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nr-bank-app.name" . }}
    spec:
      containers:
      - name: {{ include "nr-bank-app.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        env:
        - name: NEW_RELIC_LICENSE_KEY
          value: "{{ .Values.newRelic.licenseKey }}"
