apiVersion: v1
kind: Service
metadata:
  name: {{ include "nr-bank-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "nr-bank-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}
